import type { Product } from "@/types/product";

export const featuredCategories = [
  "Electronics",
  "Fashion",
  "Home & Living",
  "Beauty",
  "Sports",
  "Groceries",
  "Office",
  "Automotive",
];

export const allHomeProducts: Product[] = [
  {
    id: "p-1",
    name: "16TB USB 3.2 Flash Drive",
    slug: "16tb-usb-3-2-flash-drive",
    category: "Electronics",
    brand: "ByteCore",
    imageUrl:
      "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?auto=format&fit=crop&w=1200&q=80",
    price: 3890,
    oldPrice: 4790,
    rating: 4.3,
    reviewsCount: 120,
    inStock: true,
    shortDescription: "High-speed compact storage with durable metal body.",
  },
  {
    id: "p-2",
    name: "Bluetooth Smart Glasses",
    slug: "bluetooth-smart-glasses",
    category: "Electronics",
    brand: "VisionLab",
    imageUrl:
      "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=1200&q=80",
    price: 26870,
    oldPrice: 36170,
    rating: 4.5,
    reviewsCount: 251,
    inStock: true,
    shortDescription: "Open-ear audio eyewear with blue light protection.",
  },
  {
    id: "p-3",
    name: "Premium Earbuds Pro",
    slug: "premium-earbuds-pro",
    category: "Electronics",
    brand: "LenoWave",
    imageUrl:
      "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=1200&q=80",
    price: 3180,
    oldPrice: 7360,
    rating: 4.3,
    reviewsCount: 500,
    inStock: true,
    shortDescription: "Noise isolation earbuds with fast charging case.",
  },
  {
    id: "p-4",
    name: "Original Laptop Cooling Pads",
    slug: "original-laptop-cooling-pads",
    category: "Electronics",
    brand: "Youwena",
    imageUrl:
      "https://images.unsplash.com/photo-1618761714954-0b8cd0026356?auto=format&fit=crop&w=1200&q=80",
    price: 6280,
    oldPrice: 6780,
    rating: 4.7,
    reviewsCount: 1700,
    inStock: true,
    shortDescription: "Dual-fan cooling stand for gaming and office laptops.",
  },
  {
    id: "p-5",
    name: "Xiaomi Gift Memory Box",
    slug: "xiaomi-gift-memory-box",
    category: "Electronics",
    brand: "Xiaomi",
    imageUrl:
      "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=1200&q=80",
    price: 1220,
    oldPrice: 2890,
    rating: 4.9,
    reviewsCount: 1700,
    inStock: true,
    shortDescription: "Accessory box with storage and cable management.",
  },
  {
    id: "p-6",
    name: "Gaming Mechanical Keyboard",
    slug: "gaming-mechanical-keyboard",
    category: "Electronics",
    brand: "HyperInput",
    imageUrl:
      "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=1200&q=80",
    price: 12490,
    oldPrice: 16990,
    rating: 4.6,
    reviewsCount: 640,
    inStock: true,
    shortDescription: "RGB keyboard with tactile blue switches and metal frame.",
  },
  {
    id: "p-7",
    name: "USB-C Hub Multi Port 9-in-1",
    slug: "usb-c-hub-multi-port-9-in-1",
    category: "Electronics",
    brand: "DockEdge",
    imageUrl:
      "https://images.unsplash.com/photo-1625842268584-8f3296236761?auto=format&fit=crop&w=1200&q=80",
    price: 5390,
    oldPrice: 8990,
    rating: 4.5,
    reviewsCount: 430,
    inStock: true,
    shortDescription: "HDMI, USB, SD card and fast PD charging in one hub.",
  },
  {
    id: "p-8",
    name: "Smartwatch Active X",
    slug: "smartwatch-active-x",
    category: "Electronics",
    brand: "PulseTech",
    imageUrl:
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80",
    price: 11205,
    oldPrice: 14744,
    rating: 4.4,
    reviewsCount: 970,
    inStock: true,
    shortDescription: "Fitness tracking watch with AMOLED display and GPS.",
  },
  {
    id: "p-9",
    name: "Camo Waterproof Blanket",
    slug: "camo-waterproof-blanket",
    category: "Sports",
    brand: "TrailLock",
    imageUrl:
      "https://images.unsplash.com/photo-1475483768296-6163e08872a1?auto=format&fit=crop&w=1200&q=80",
    price: 30950,
    oldPrice: 65686,
    rating: 4.2,
    reviewsCount: 212,
    inStock: true,
    shortDescription: "Outdoor all-weather blanket for camping and trekking.",
  },
  {
    id: "p-10",
    name: "Motorcycle Jacket Urban Ride",
    slug: "motorcycle-jacket-urban-ride",
    category: "Fashion",
    brand: "RoadCore",
    imageUrl:
      "https://images.unsplash.com/photo-1521223890158-f9f7c3d5d504?auto=format&fit=crop&w=1200&q=80",
    price: 35240,
    oldPrice: 58090,
    rating: 4.6,
    reviewsCount: 316,
    inStock: true,
    shortDescription: "Protective jacket with reinforced shoulders and vents.",
  },
  {
    id: "p-11",
    name: "Wireless Charger Stand",
    slug: "wireless-charger-stand",
    category: "Electronics",
    brand: "VoltFix",
    imageUrl:
      "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?auto=format&fit=crop&w=1200&q=80",
    price: 3990,
    oldPrice: 5590,
    rating: 4.4,
    reviewsCount: 284,
    inStock: true,
    shortDescription: "Fast wireless charging dock with anti-slip design.",
  },
  {
    id: "p-12",
    name: "Portable Blender GoMix",
    slug: "portable-blender-gomix",
    category: "Home & Living",
    brand: "HomeMix",
    imageUrl:
      "https://images.unsplash.com/photo-1570222094114-d054a817e56b?auto=format&fit=crop&w=1200&q=80",
    price: 6990,
    oldPrice: 8990,
    rating: 4.5,
    reviewsCount: 199,
    inStock: true,
    shortDescription: "Rechargeable mini blender for smoothies on the go.",
  },
  {
    id: "p-13",
    name: "Vitamin C Day Cream",
    slug: "vitamin-c-day-cream",
    category: "Beauty",
    brand: "GlowNest",
    imageUrl:
      "https://images.unsplash.com/photo-1614859475297-0b85f5f60276?auto=format&fit=crop&w=1200&q=80",
    price: 2790,
    oldPrice: 3590,
    rating: 4.8,
    reviewsCount: 621,
    inStock: true,
    shortDescription: "Hydrating brightening cream for daily skincare.",
  },
  {
    id: "p-14",
    name: "Minimal Desk Lamp",
    slug: "minimal-desk-lamp",
    category: "Home & Living",
    brand: "LightNova",
    imageUrl:
      "https://images.unsplash.com/photo-1543198126-a8ad8e47fb22?auto=format&fit=crop&w=1200&q=80",
    price: 4890,
    oldPrice: 6790,
    rating: 4.4,
    reviewsCount: 182,
    inStock: true,
    shortDescription: "Eye-care LED desk lamp with touch brightness control.",
  },
  {
    id: "p-15",
    name: "Travel Duffel Bag",
    slug: "travel-duffel-bag",
    category: "Fashion",
    brand: "UrbanMark",
    imageUrl:
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1200&q=80",
    price: 9490,
    oldPrice: 12490,
    rating: 4.6,
    reviewsCount: 348,
    inStock: true,
    shortDescription: "Large-capacity water-resistant bag for short trips.",
  },
  {
    id: "p-16",
    name: "Protein Shaker Steel",
    slug: "protein-shaker-steel",
    category: "Sports",
    brand: "FitCore",
    imageUrl:
      "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1200&q=80",
    price: 2390,
    oldPrice: 3190,
    rating: 4.1,
    reviewsCount: 96,
    inStock: true,
    shortDescription: "Leak-proof steel shaker bottle with measurement marks.",
  },
  {
    id: "p-17",
    name: "Office Ergonomic Chair",
    slug: "office-ergonomic-chair",
    category: "Office",
    brand: "WorkEase",
    imageUrl:
      "https://images.unsplash.com/photo-1505843513577-22bb7d21e455?auto=format&fit=crop&w=1200&q=80",
    price: 42990,
    oldPrice: 49990,
    rating: 4.7,
    reviewsCount: 145,
    inStock: true,
    shortDescription: "Lumbar support office chair for long work sessions.",
  },
  {
    id: "p-18",
    name: "Car Phone Holder Pro",
    slug: "car-phone-holder-pro",
    category: "Automotive",
    brand: "DriveSafe",
    imageUrl:
      "https://images.unsplash.com/photo-1489824904134-891ab64532f1?auto=format&fit=crop&w=1200&q=80",
    price: 1990,
    oldPrice: 2890,
    rating: 4.2,
    reviewsCount: 411,
    inStock: true,
    shortDescription: "Dashboard magnetic mount with 360-degree rotation.",
  },
];

export const featuredProducts = allHomeProducts.slice(0, 12);
export const trendingProducts = allHomeProducts.slice(4, 14);
export const dealProducts = allHomeProducts.filter((_, index) => index % 2 === 0).slice(0, 10);
export const offerProducts = allHomeProducts.filter((_, index) => index % 2 !== 0).slice(0, 10);

